:source-highlighter: highlightjs
:numbered:

= Exemplo de Aplicação REST utilizando Java com API JAX-RS e Servidor de Aplicação Thorntail

== Requisitos

Tenha certeza de rodar a aplicação com no máximo o JDK 8.
Os servidores de aplicação normalmente ainda não funcionam com versões mais recentes do JDK.

== Executar o Projeto

Existem diferentes maneiras de executar este projeto.

== Ambiente de Desenvolvimento 

=== Iniciar o servidor Thorntail

Você pode iniciar o servidor Thorntail com a sua aplicação de diferentes maneiras:

- Usando o plugin thorntail incluído no projeto: `mvn clean thorntail:run`.
- Como foi incluído o arquivo link:nbactions.xml[nbactions.xml], o comando anterior pode
ser executado clicando-se com o botão direito sobre o nome do projeto no NetBeans
e escolhendo "Run Maven >> clean thorntail:run".
- Manualmente compilando o projeto e executando o fat jar criado (um jar com o servidor e sua app, tudo junto): `mvn clean package; java -jar target/rest-app-thorntail.jar`.

=== Atualizando o projeto sem reiniciar o servidor

Depois de ter iniciado o servidor e fazer alterações no projeto, 
para fazer o deploy (implantar a aplicação no servidor) não precisamos reiniciar o servidor.
Mais uma vez, isso pode ser feito de diferentes maneiras:

- Usando o perfil "redeploy" criado no projeto Maven quando for recompilar seu projeto (): `mvn package -Predeploy`.
- O projeto foi configurado no NetBeans para usar um comando personalizado
  para executar a aplicação (uma vez que não estamos usando um servidor convencional
  como o GlassFish). Assim, ao clicar no botão "Play" (ou pressionar F6), o comando
  acima será executado.

=== Executando a aplicação

Se você estiver habituado a usar servidores como o GlassFish no NetBeans, sabe que ao clicar no botão Play, o projeto é compilado e executado, abrindo o navegador automaticamente.
Com servidores de aplicação como o Thorntail isso não ocorrerá.
Você deve abrir o navegador você mesmo. Neste caso, a aplicação estará disponível
em http://localhost:8080. Observe que não há um caminho adicional com o nome da aplicação no final da URL, pois a aplicação executa na raiz do servidor.

== Ambiente de Produção

Tendo enviado o fat jar para o ambiente de produção, basta digitar `java -jar rest-app-thorntail.jar`,
assim como inicia-se qualquer jar executável em Java. Isto vai iniciar o servidor Thorntail com sua aplicação.

== Referências

- http://docs.thorntail.io
- https://github.com/thorntail/thorntail-examples/tree/master/jpa-jaxrs-cdi/jpa-jaxrs-cdi-jta
- https://github.com/manoelcampos/thorntail-sample-projects
