:source-highlighter: highlightjs
:imagesdir: images
:numbered:
:unsafe:

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= Exemplo de Servidor REST utilizando Java com API JAX-RS e Thorntail App Server

== Executar o Projeto

Após compilar o projeto, na pasta target será gerado um pacote `rest-server-thorntail.jar`.
Este pacote contém o App Server Thorntail, sua aplicação e todas as dependências
e configurações necessárias.

Para iniciar a aplicação no ambiente de desenvolvimento (juntamente com o App Server), basta
executar o comando `mvn thorntail:run`.

Se estiver no ambiente de produção, basta digitar `java -jar rest-server-thorntail.jar`,
assim como inicia-se qualquer jar executável em Java.

No entanto, qualquer uma das duas opções requer que que a aplicação seja empacotada (criado um jar e/ou war), o que é um processo lento. Se desejar rodar a aplicação diretamente
das classes compiladas na pasta `target`, basta executar `java -cp target/rest-server-thorntail.jar:target/classes org.wildfly.swarm.bootstrap.Main`.

Se quiser rodar a aplicação de forma mais rápida a partir de um IDE como o NetBeans,
basta executar a classe `StartThorntail` no pacote `com.manoelcampos.server.config`. 
As configurações do classpath já foram
feitas para o NetBeans (ver arquivo nbactions.xml).

Tenha certeza de rodar a aplicação com no máximo o JDK 8.
Os servidores de aplicação normalmente ainda não funcionam com versões mais novas do JDK.

== Referências

- https://github.com/thorntail/thorntail-examples/tree/master/jpa-jaxrs-cdi/jpa-jaxrs-cdi-jta