:source-highlighter: highlightjs
:numbered:

= Exemplo de Aplicação REST utilizando Java com API JAX-RS e Servidor de Aplicação Thorntail

== Executar o Projeto

Existem diferentes maneiras de executar este projeto.

== Ambiente de Desenvolvimento 

Para iniciar o Throntail com nossa aplicação, basta executar o comando `mvn clean thorntail:run`.
Como foi incluído o arquivo link:nbactions.xml[nbactions.xml], tal comando pode
ser executado clicando-se com o botão direito sobre o nome do projeto no NetBeans
e escolhendo "Run Maven >> clean thorntail:run".

== Ambiente de Produção

Se estiver no ambiente de produção, basta digitar `java -jar rest-server-thorntail.jar`,
assim como inicia-se qualquer jar executável em Java.

No entanto, qualquer uma das duas opções requer que que a aplicação seja empacotada (criado um jar e/ou war), o que é um processo lento. Se desejar rodar a aplicação diretamente
das classes compiladas na pasta `target`, basta executar:
`java -cp target/rest-server-thorntail.jar:target/classes org.wildfly.swarm.bootstrap.Main`.

== Acessando o Sistema

Após executar, a aplicação poderá ser acessada em http://localhost:8080

Tenha certeza de rodar a aplicação com no máximo o JDK 8.
Os servidores de aplicação normalmente ainda não funcionam com versões mais novas do JDK.

== Referências

- http://docs.thorntail.io
- https://github.com/thorntail/thorntail-examples/tree/master/jpa-jaxrs-cdi/jpa-jaxrs-cdi-jta
- https://docs.thorntail.io/4.0.0-SNAPSHOT/#devtools[Hot deploy (Hot reload)]
