:source-highlighter: highlightjs
:icons: font
:numbered:
:listing-caption: Listagem
:figure-caption: Figura

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= Web Services

== Introdução

Fornece uma https://www.icloud.com/keynote/0a2Oz1bSmqfwIY17tynx1kuvQ#introducao-webservices[apresentação] que dá uma visão geral sobre Web Services.
Disponibiliza projetos que implementam e consomem (acessam/utilizam) Serviços Web no padrão REST.

O Capítulo 2 da minha dissertação de mestrado, que trata especificamente da tecnologia de Web Services e os
padrões conhecidos, é disponibilizado link:dissertacao-mestrado-cap2-web-services.pdf[aqui]. 
Tal capítulo contém informações resumidas, apresentando apenas as partes importantes das tecnologias de Web Services.

O script link:consulta-cep.sh[consulta-cep.sh] é um exemplo de como acessar o Web Service de consulta
de endereços a partir do CEP, disponibilizado pelos Correios.
A intenção do script é apenas mostrar como é a requisição SOAP sendo trafegada via HTTP e como é a resposta obtida.

Veja as sub-pastas dos projetos para detalhes.

== Web Services REST

Esta https://www.icloud.com/keynote/0f4FNPAYyW-bs64ox7v2jSI-w#rest[apresentação] mostra detalhes do estilo arquitetural REST.
Um resumo dos principais termos e características,
baseado na tese de doutorado de Roy Fielding (criador do REST),
está disponível link:REST.adoc[aqui].

== Projeto de exemplo de API REST com SpringBoot para uma Loja Virtual 

https://github.com/manoelcampos/loja-virtual-springboot-rest

== Material Complementar

Acesse o https://github.com/manoelcampos/sd-web-services/wiki[Wiki] para consultar materiais complementares.
