:source-highlighter: highlightjs
:icons: font
:numbered:
:listing-caption: Listagem
:figure-caption: Figura

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= Web Services

== Introdução

Fornece uma link:webservices.pptx[apresentação] que dá uma visão geral sobre Web Services.
Disponibiliza projetos que implementam e consomem (acessam/utilizam) Serviços Web no padrão REST.

O Capítulo 2 da minha dissertação de mestrado, que trata especificamente da tecnologia de Web Services e os
padrões conhecidos, é disponibilizado link:dissertacao-mestrado-cap2-web-services.pdf[aqui]. 
Tal capítulo contém informações resumidas, apresentando apenas as partes importantes das tecnologias de Web Services.

O script link:consulta-cep.sh[consulta-cep.sh] é um exemplo de como acessar o Web Service de consulta
de endereços a partir do CEP, disponibilizado pelos Correios.
A intenção do script é apenas mostrar como é a requisição SOAP sendo trafegada via HTTP e como é a resposta obtida.

Veja as sub-pastas dos projetos para detalhes.

== Web Services REST

Esta link:rest.pptx[apresentação] mostra detalhes do estilo arquitetural REST.
Um resumo dos principais termos e características,
baseado na tese de doutorado de Roy Fielding (criador do REST),
está disponível link:REST.adoc[aqui].

== Projetos

- link:4.3-ws-rest-cryptocoins-client[Web app que obtém a cotação do BitCoin a partir do serviço REST do CoinMarketCap]
- link:4.4-ws-rest-cadastro[Tutorial e projeto de criação de serviços REST com JavaEE, JAX-RS, CDI e JPA]
- https://github.com/manoelcampos/sd-webservices/tree/quarkus[Web Service REST em Java utilizando o framework Quarkus com as mesmas tecnologias do link acima]

== Material Complementar

Acesse o https://github.com/manoelcampos/sd-web-services/wiki[Wiki] para consultar materiais complementares.
