:source-highlighter: highlightjs
:numbered:

= Exemplo de Aplicação REST utilizando Java com JAX-RS, CDI, JPA e o framework Quarkus

Se você chegou até aqui e não sabe o que é https://quarkus.io[Quarkus], veja o projeto anterior link:../4.5-ws-rest-quarkus-framework[aqui]. Este projeto é baseado na estrutura do anterior.

Esta versão inclui suporte à injeção de dependências com CDI e acesso à banco de dados com a Java Persistence API (JPA) utilizando o framework Hibernate.

== Requisitos

Além do JDK 8 e Maven 3.5.3 ou superior, este projeto usa o MySQL/MariaDB como banco de dados.
No entanto, você pode utilizar qualquer banco que desejar, desde que faça as configurações adequadas para o banco escolhido.

== Detalhes do Projeto

Foi incluído o arquivo link:src/main/webapp/WEB-INF/beans.xml[beans.xml] para configurar o CDI. Tal arquivo não é necessário desde o Java EE 7 e de fato o Quarkus parece estar ignorando o mesmo (ou ele não foi colocado na pasta correta).

As configurações do DataSource para conexão com o banco foram feitas no arquivo link:src/main/resources/application.properties[application.properties] e não no persistence.xml. Apesar de ser possível utilizar o persistence.xml como usual, você não pode incluir os dois arquivos no projeto. De qualuqer forma, a configuração pelo application.properties é muito mais simples.

Veja que como o servidor será embutido na nossa aplicação, precisamos indicar qual o banco de dados será usado, incluíndo uma dependência para isso no pom.xml. Neste caso o banco de dados usado pode ser o MariaDB ou MySQL. Assim foi incluída a dependência `quarkus-jdbc-mariadb`. Observe que, apesar de tal dependência ser para o MariaDB, ela funciona com o MySQL (pois o MariaDB é apenas um fork do MySQL).
Mas para isto, foi preciso definir no application.properties que desejamos usar o dialeto SQL do MySQL.
Neste caso, como estou utilizando MySQL 8, foi definida a classe `org.hibernate.dialect.MySQL8Dialect` no application.properties. Se estiver usando uma versão diferente do MySQL, pode consultar o nome da classe que implementa o dialeto da sua versão https://docs.jboss.org/hibernate/stable/orm/javadocs/org/hibernate/dialect/package-summary.html[aqui].

Certifique-se de criar o banco com o nome indicado no application.properties e indicar o nome de usuário e senha do servidor de banco de dados, além de outras possíveis configurações para o seu banco.

Por fim, que as dependências que normalmente incluímos em um projeto JavaEE com Hibernate seriam javax.javaee-web-api, org.hibernate.javax.persistence e possivelmente outras dependências relacionadas a API JAX-RS e processamento de JSON. Ao usar um framework como o Quarkus que embute um servidor na própria aplicação, tais dependências não devem ser incluídas do modo tradicional (usando os pacotes fornecidos pelo desenvolvedor destas bibliotecas), mas sim as versões de tais bibliotecas disponibilizadas por ferramentas como o Quarkus.

Assim, veja que no link:pom.xml[pom.xml] que tais bibliotecas usadas foram fornecidas pelo próprio Quarkus.

== Executar o Projeto

== Ambiente de Desenvolvimento 

=== Iniciando o servidor

Você pode iniciar o servidor com sua aplicação de diferentes maneiras:

- Usando o script mvnw incluído durante a criação do projeto: `./mvnw compile quarkus:dev`.
- Ou simplesmente clicando no botão Play em IDEs como o NetBeans, pois foi incluído o plugin maven exec para executar o comando acima mais facilmente.

=== Atualizando o projeto sem reiniciar o servidor

Bem, atualizar o projeto no servidor em execução e ver as alterações que você fez na sua aplicação é realmente complicado com o Quarkus: você precisa apenas salvar o projeto e boom: normalmente em menos de 1 segundo a aplicação estará rodando com as novas alterações 😱🚀😁.

Não é à toa que o slogan do Quarkus é "Supersonic Subatomic Java".

=== Acessando a aplicação

Se você estiver habituado a usar servidores como o GlassFish no NetBeans, sabe que ao clicar no botão Play, o projeto é compilado e executado, abrindo o navegador automaticamente.
Usando o Quarkus isso não ocorrerá.
Você deve abrir o navegador você mesmo. Neste caso, a aplicação estará disponível
em http://localhost:8080. Observe que não há um caminho adicional com o nome da aplicação no final da URL, pois a aplicação executa na raiz do servidor.

== Ambiente de Produção

Para enviar a aplicação para um ambiente de produção você deve executar `./mvnw clean package` em um terminal na raiz do projeto para criar o que chamamos de fat jar: um jar contendo a aplicação e o servidor que executará a própria aplicação.

Com o comando acima o pacote `target/rest-app-quarkus-server-runner.jar` é criado e a partir dele podemos iniciar o servidor com a aplicação usando:

`java -jar target/rest-app-quarkus-server-runner.jar`

Assim, este é o pacote que precisa enviar para o ambiente de produção. 
Possíveis bibliotecas que a aplicação não estão sendo empacotadas neste jar.
Posteriormente atualizo o projeto para fazer isso.

=== Container Docker

Para gerar um container docker com tudo necessário para executar a aplicação, é preciso ter a https://graalvm.org[GraalVM] e o https://www.docker.com/products/docker-desktop[Docker] instalados. 
O Docker precisa estar rodando na máquina de desenvolvimento para construir a imagem do container.
Em seguida, basta executar os comandos abaixo:

```bash
./mvnw package -Pnative -Dnative-image.docker-build=true
docker build -f src/main/docker/native.Dockerfile -t com.manoelcampos/rest-app-quarkus-server .
```

Observe que `com.manoelcampos/rest-app-quarkus-server` é apenas uma tag para categorizar
a imagem docker criada. Você pode usar qualquer nome que quiser, seguindo o padrão
desenvolvedor/descricao_imagem. Para aplicações java, um padrão comum é nome_do_pacote/nome_aplicacao.

Agora, executando `docker image list` será exibida a lista de imagens docker disponíveis.
A imagem `com.manoelcampos/rest-app-quarkus-server` (no caso do exemplo acima) deverá ser exibida na lista.

Você pode ver as imagens criadas com:

`docker image list`

Uma imagem com o nome "com.manoelcampos/rest-app-quarkus-server" (ou qualquer nome que você tenha dado) deve aparecer na lista. Note que a imagem docker contendo a aplicação inteira, incluindo o servidor, terá menos de 40MB. Só a versão básica do GlassFish tem 60MB. O GlassFish Full tem cerca de 120MB.

Você pode iniciar um container a partir de tal imagem com o comando:

`docker run -i --rm -p 8080:8080 com.manoelcampos/rest-app-quarkus-server`

A partir de então, a aplicação poderá ser acessada de dentro do container pelo endereço http://localhost:8080.

== Referências

- https://quarkus.io
- https://quarkus.io/guides/getting-started-guide
- https://quarkus.io/guides/building-native-image-guide
- https://quarkus.io/guides/rest-json-guide
- https://lordofthejars.github.io/quarkus-cheat-sheet/