:source-highlighter: highlightjs
:numbered:

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= Exemplo de Aplicação REST utilizando Java com JAX-RS, CDI, JPA e o framework Quarkus

Se você chegou até aqui e não sabe o que é https://quarkus.io[Quarkus], veja o link:../4.5-ws-rest-quarkus-framework[projeto anterior]. Este projeto é baseado na estrutura do anterior.

Esta versão inclui suporte à injeção de dependências com CDI e acesso à banco de dados com a Java Persistence API (JPA) utilizando o framework Hibernate.

== Requisitos

Além do JDK 8 e Maven 3.5.3 ou superior, este projeto usa o MySQL/MariaDB como banco de dados.
No entanto, você pode utilizar qualquer banco que desejar, desde que faça as configurações adequadas para o banco escolhido. Para isto, é preciso incluir o driver JDBC para o seu banco a partir das dependências do Quarkus no pom.xml. Para o MySQL/MariaDB foi incluído:

[source,xml]
----

    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-jdbc-mariadb</artifactId>
    </dependency>
----

As configurações da conexão devem ser definidas em arquivo link:src/main/resources/application.properties[application.properties].

== Detalhes do Projeto

Foi incluído o arquivo link:src/main/webapp/WEB-INF/beans.xml[beans.xml] para configurar o CDI. Tal arquivo não é necessário desde o Java EE 7 e de fato o Quarkus parece estar ignorando o mesmo (ou ele não foi colocado na pasta correta).

As configurações do DataSource para conexão com o banco foram feitas no arquivo link:src/main/resources/application.properties[application.properties] e não no persistence.xml. Apesar de ser possível utilizar o persistence.xml como usual, você não pode incluir os dois arquivos no projeto. De qualuqer forma, a configuração pelo application.properties é muito mais simples.

Veja que como o servidor será embutido na nossa aplicação, precisamos indicar qual o banco de dados será usado, incluíndo uma dependência para isso no pom.xml. Neste caso o banco de dados usado pode ser o MariaDB ou MySQL. Assim foi incluída a dependência `quarkus-jdbc-mariadb`. Observe que, apesar de tal dependência ser para o MariaDB, ela funciona com o MySQL (pois o MariaDB é apenas um fork do MySQL).
Mas para isto, foi preciso definir no application.properties que desejamos usar o dialeto SQL do MySQL.
Neste caso, como estou utilizando MySQL 8, foi definida a classe `org.hibernate.dialect.MySQL8Dialect` no application.properties. Se estiver usando uma versão diferente do MySQL, pode consultar o nome da classe que implementa o dialeto da sua versão https://docs.jboss.org/hibernate/stable/orm/javadocs/org/hibernate/dialect/package-summary.html[aqui].

Certifique-se de criar o banco com o nome indicado no application.properties e indicar o nome de usuário e senha do servidor de banco de dados, além de outras possíveis configurações para o seu banco.

Por fim, que as dependências que normalmente incluímos em um projeto JavaEE com Hibernate seriam javax.javaee-web-api, org.hibernate.javax.persistence e possivelmente outras dependências relacionadas a API JAX-RS e processamento de JSON. Ao usar um framework como o Quarkus que embute um servidor na própria aplicação, tais dependências não devem ser incluídas do modo tradicional (usando os pacotes fornecidos pelo desenvolvedor destas bibliotecas), mas sim as versões de tais bibliotecas disponibilizadas por ferramentas como o Quarkus.

Assim, veja que no link:pom.xml[pom.xml] que tais bibliotecas usadas foram fornecidas pelo próprio Quarkus.

== Executar o Projeto

== Ambiente de Desenvolvimento 

=== Iniciando o servidor

Você pode iniciar o servidor com sua aplicação de diferentes maneiras:

- Usando o script mvnw incluído durante a criação do projeto: `./mvnw compile quarkus:dev`.
- Ou simplesmente clicando no botão Play em IDEs como o NetBeans, pois foi incluído o plugin maven exec para executar o comando acima mais facilmente.

=== Atualizando o projeto sem reiniciar o servidor

Bem, atualizar o projeto no servidor em execução e ver as alterações que você fez na sua aplicação é realmente complicado com o Quarkus: você precisa apenas salvar o projeto e boom: normalmente em menos de 1 segundo a aplicação estará rodando com as novas alterações 😱🚀😁.

Não é à toa que o slogan do Quarkus é "Supersonic Subatomic Java".

=== Acessando a aplicação

Se você estiver habituado a usar servidores como o GlassFish no NetBeans, sabe que ao clicar no botão Play, o projeto é compilado e executado, abrindo o navegador automaticamente.
Usando o Quarkus isso não ocorrerá.
Você deve abrir o navegador você mesmo. Neste caso, a aplicação estará disponível
em http://localhost:8080. Observe que não há um caminho adicional com o nome da aplicação no final da URL, pois a aplicação executa na raiz do servidor.

== Ambiente de Produção

Para enviar a aplicação para um ambiente de produção você deve executar `./mvnw clean package` em um terminal na raiz do projeto para criar o que chamamos de uber jar. Este é um tipo de jar que contém tudo que a aplicação precisa para executar:

- a própria aplicação;
- o servidor que executará a aplicação;
- todas as dependências necessárias (arquivos jar das bibliotecas usadas).

Com o comando acima o pacote `target/rest-app-quarkus-server-jpa-runner.jar` é criado e a partir dele podemos iniciar o servidor com a aplicação. Assim, este é o *único* pacote que precisa ser enviado para o ambiente de produção. 

=== Configurações no Ambiente de Produção.

Observe que o arquivo link:src/main/resources/application.properties[application.properties]
possui variáveis iniciando com `%dev.` e outras com `%prod.`, para indicar,
respectivamente, configurações para o ambiente de desenvolvimento e ambiente de produção.
Normalmente teremos configurações distintas em tais ambientes, como:

- diferente IP do servidor de banco de dados e posssivelmente diferente usuário e senha;
- diferente porta para rodar o servidor de aplicação (normalmente 8080 em desenvolvimento e 80 em produção).

Assim, para indicar que deseja rodar a aplicação no ambiente de produção, existem diversas maneiras,
como criar uma variável de ambiente com o comando `export QUARKUS_PROFILE=prod`. Em linux, tal comando pode ser incluído em arquivos como o `~/.bashrc`, `~/.bash_profile` ou `~/.profile`. Assim, ao logar no servidor com o usuário que usou para editar algum destes arquivos, a variável já será criada.

IMPORTANT: Certifique-se que o arquivo que você escolheu acima realmente existe. Se não existir, tente um dos outros arquivos.

Após editar um dos arquivos acima, é preciso executá-lo para a variável ser de fato criada.
Se incluiu a linha acima no arquivo `~/.profile`, deverá executar `source ~/.profile` para isto.

Como no arquivo application.properties foi definido que no ambiente de produção
será usada a porta 80, no Linux é preciso usar root para executar a aplicação:

[source,bash]
----
sudo java -jar rest-app-quarkus-server-jpa-runner.jar
----

Ao rodar a aplicação agora, ela vai entender que está no ambiente de produção e usar as configurações de tal ambiente a partir do arquivo application.properties.

=== Container Docker

Para gerar containers com tudo necessário para executar a aplicação, e assim facilitar a implantação (deploy) dela, veja esta link:docker-container.adoc[página]. 

== Referências

- https://quarkus.io
- https://quarkus.io/guides/getting-started-guide
- https://quarkus.io/guides/building-native-image-guide
- https://quarkus.io/guides/rest-json-guide
- https://lordofthejars.github.io/quarkus-cheat-sheet/
- https://quarkus.io/guides/application-configuration-guide