:source-highlighter: highlightjs
:numbered:

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= Exemplo de Aplicação REST utilizando Java com JAX-RS, CDI, JPA e o framework Quarkus (link:https://kinolien.github.io/gitzip/?download=/manoelcampos/sd-webservices/tree/master/4.5-ws-rest-quarkus-jpa[zip])

Este projeto usa o framework https://quarkus.io[Quakus] para compilar e executar uma aplicação
java web que disponibiliza serviços REST utilizando a API JAX-RS.

O Quarkus é o que há de mais recente e moderno para o desenvolvimento e execução
de  aplicações Jakarta EE (antigo Java EE).
Ele permite compilar o código Java para código nativo usando a https://graalvm.org[GraalVM]
no lugar da JVM. A GraalVM é também um projeto recente que permite compilar aplicações em uma infinidade de linguagens para código nativo. A lista de linguagens é extensa e inclui JavaScript (e Node.js), Python, Ruby, Java, Scala, Groovy, Kotlin, etc.

O projeto inclui acesso à banco de dados com a Java Persistence API (JPA) utilizando o framework Hibernate
por meio da biblioteca https://quarkus.io/guides/hibernate-orm-panache[Panache].
Tal biblioteca praticamente elimina a necessidade de criarmos DAOs para implementar o acesso ao BD,
além de reduzir drasticamente a quantidade de código das classes de negócio.
Veja a documentação das classes no pacote `model` para mais detalhes.

== Requisitos

=== Ferramentas

O projeto requer JDK 8 ou 11 e Maven 3.6.3 ou superior.
Mesmo as versões mais atuais do NetBeans vêm com versões antigas do Maven que não irá funcionar.

O maven pode ser instalado, por exemplo em distribuições Linux baseadas em Debian, com:

[source,bash]
----
sudo apt-get install maven
----

No Windows, pode-se baixar um arquivo `apache-maven-x.x.x-bin.zip` em https://maven.apache.org/download.cgi. Você também pode configurar o https://docs.microsoft.com/en-us/windows/wsl/install-win10[Windows Subsystem for Linux] e assim poderá baixar aplicações usando o mesmo comando Linux acima.

No NetBeans então é possível indicar que deseja-se utilizar uma versão do Maven instalada no sistema, no lugar de usar a que vem com o NetBeans. 
Para isto, acesse as preferências do NetBeans, depois a aba Java >> Maven e informe o caminho do comando "mvn" no campo "Maven Home".

=== Banco de Dados

O projeto usa um banco de dados em memória do Apache H2, recriando e populando o banco a cada vez que a aplicação é iniciada.
No entanto, você pode utilizar qualquer banco que desejar, desde que faça as configurações adequadas para o banco escolhido. Para isto, é preciso incluir o driver JDBC para o seu banco a partir das dependências do Quarkus no pom.xml. 

As configurações da conexão devem ser definidas no arquivo link:src/main/resources/application.properties[application.properties].

== Criação do Projeto

Toda a estrutura deste projeto foi criada automaticamente. A forma mais fácil de fazer isso é por meio do site http://code.quarkus.io. Assim, tal site pode ser o ponto de partida para a criação de novos projetos.


== Detalhes do Projeto

As configurações do DataSource para conexão com o banco foram feitas no arquivo link:src/main/resources/application.properties[application.properties] e não no persistence.xml. Apesar de ser possível utilizar o persistence.xml como usual, você não pode incluir os dois arquivos no projeto. De qualuqer forma, a configuração pelo application.properties é muito mais simples.

Veja que como o servidor será embutido na nossa aplicação, precisamos indicar qual o banco de dados será usado, incluíndo uma dependência para isso no pom.xml. Neste caso o banco de dados usado foi o Apache H2 em memória. Assim foi incluída a dependência `quarkus-jdbc-h2`. 

Por fim, que as dependências que normalmente incluímos em um projeto JavaEE com Hibernate seriam javax.javaee-web-api, org.hibernate.javax.persistence e possivelmente outras dependências relacionadas a API JAX-RS e processamento de JSON. Ao usar um framework como o Quarkus que embute um servidor na própria aplicação, tais dependências não devem ser incluídas do modo tradicional (usando os pacotes fornecidos pelo desenvolvedor destas bibliotecas), mas sim as versões de tais bibliotecas disponibilizadas por ferramentas como o Quarkus.

Assim, veja que no link:pom.xml[pom.xml] que tais bibliotecas usadas foram fornecidas pelo próprio Quarkus.

== Executar o Projeto

=== Ambiente de Desenvolvimento 

Você pode iniciar o servidor com sua aplicação de diferentes maneiras.

==== Usando Maven pela linha de comando

```bash
mvn compile quarkus:dev
```

==== Usando o maven-exec-plugin

Você pode clicar no botão Play em IDEs como o NetBeans, pois foi incluído o plugin maven-exec para executar o comando acima mais facilmente.
Caso você esteja criando o projeto do zero, o plugin maven-exec não será incluído
e você deve incluí-lo dentro da tag `<plugins>` no arquivo pom.xml, como
mostrado abaixo:

```xml
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>exec-maven-plugin</artifactId>
  <version>1.6.0</version>
  <configuration>
    <executable>mvn</executable>
    <arguments>
      <argument>clean</argument>
      <argument>compile</argument>
      <argument>quarkus:dev</argument>
    </arguments>
  </configuration>
</plugin>
```

==== Atualizando o projeto sem reiniciar o servidor

Bem, atualizar o projeto no servidor em execução e ver as alterações que você fez na sua aplicação é realmente complicado com o Quarkus: você precisa apenas salvar o projeto e boom: normalmente em menos de 1 segundo a aplicação estará rodando com as novas alterações 😱🚀😁.

Não é à toa que o slogan do Quarkus é "Supersonic Subatomic Java".

==== Acessando a aplicação

Se você estiver habituado a usar servidores como o GlassFish no NetBeans, sabe que ao clicar no botão Play, o projeto é compilado e executado, abrindo o navegador automaticamente.
Usando o Quarkus isso não ocorrerá.
Você deve abrir o navegador você mesmo. Neste caso, a aplicação estará disponível
em http://localhost:8080. Observe que não há um caminho adicional com o nome da aplicação no final da URL, pois a aplicação executa na raiz do servidor.

=== Ambiente de Produção

Para enviar a aplicação para um ambiente de produção você deve executar `./mvnw clean package` em um terminal na raiz do projeto para criar o que chamamos de uber jar. Este é um tipo de jar que contém tudo que a aplicação precisa para executar:

- a própria aplicação;
- o servidor que executará a aplicação;
- todas as dependências necessárias (arquivos jar das bibliotecas usadas).

Com o comando acima o pacote `target/rest-app-quarkus-server-jpa-runner.jar` é criado e a partir dele podemos iniciar o servidor com a aplicação. Assim, este é o *único* pacote que precisa ser enviado para o ambiente de produção. 

Para executar a aplicação em ambiente de produção, basta o comando a seguir:

[source,bash]
----
java -jar rest-app-quarkus-server-jpa-runner.jar
----

Ao rodar a aplicação agora, ela vai entender que está no ambiente de produção e usar possíveis configurações de tal ambiente a partir do arquivo application.properties.

==== Container Docker

Para gerar containers com tudo necessário para executar a aplicação, e assim facilitar a implantação (deploy) dela, veja esta link:docker-container.adoc[página]. 

=== Implantando Aplicação no Amazon Web Services (AWS)

Uma breve lista de comandos para conectar aos serviços AWS e implantar
a aplicação é mostrada nesta link:aws.adoc[página].

== Referências

- https://quarkus.io
- https://quarkus.io/guides/getting-started-guide
- https://quarkus.io/guides/building-native-image-guide
- https://quarkus.io/guides/rest-json-guide
- https://lordofthejars.github.io/quarkus-cheat-sheet/
- https://quarkus.io/guides/application-configuration-guide